services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /usr/local/bin/postgres-mock
    networks:
      - proxy

  cplane:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /usr/local/bin/cplane-mock
    environment:
      PROXY_COMPUTE_ADDR: "postgres:5432"
    networks:
      - proxy

  load:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /usr/local/bin/postgres-bench
    environment:
      PG_HOST: "neon"
      PG_ADDR: "172.16.238.10:5432"
      PG_CONNECTION_RATE: "400"
      PG_CONNECTING_MAX: "500"
      PG_CONNECTION_MAX: "8000"
    depends_on:
      - haproxy
    networks:
      - proxy

  haproxy:
    image: haproxy:2.9
    ports:
      - "5432:5432"
      - "4443:4443"
    depends_on:
      - proxy
    volumes:
      - type: bind
        source: haproxy.cfg
        target: /usr/local/etc/haproxy/haproxy.cfg
    networks:
      proxy:
        ipv4_address: 172.16.238.10

  proxy:
    image: "neondatabase/neon:release-4604"
    command:
      - proxy
      - --auth-backend
      - console
      - --auth-endpoint
      - "http://cplane:3000/authenticate_proxy_request"
      - -c
      - proxy.crt
      - -k
      - proxy.key
      - --proxy
      - "0.0.0.0:5432"
      - --mgmt
      - "0.0.0.0:8080"
      - --wss
      - "0.0.0.0:4443"
    ports:
      - "5431:5432"
      - "4442:4443"
    volumes:
      - type: bind
        source: target/proxy.crt
        target: /data/proxy.crt
      - type: bind
        source: target/proxy.key
        target: /data/proxy.key
    depends_on:
      - cplane
      - postgres
    networks:
      - proxy

networks:
  proxy:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
