services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /usr/local/bin/postgres-mock

  cplane:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /usr/local/bin/cplane-mock
    environment:
      PROXY_COMPUTE_ADDR: "postgres:5432"

  haproxy:
    build:
      context: .
      dockerfile: haproxy.Dockerfile
    ports:
      - "5432:5432"
      - "4443:4443"
    depends_on:
      - proxy

  proxy:
    image: "neondatabase/neon:release-4604"
    command:
      - proxy
      - --auth-backend
      - console
      - --auth-endpoint
      - "http://cplane:3000/authenticate_proxy_request"
      - -c
      - proxy.crt
      - -k
      - proxy.key
      - --proxy
      - "0.0.0.0:5432"
      - --mgmt
      - "0.0.0.0:8080"
      - --wss
      - "0.0.0.0:4443"
    ports:
      - "5431:5432"
      - "4442:4443"
    volumes:
      - type: bind
        source: target/proxy.crt
        target: /data/proxy.crt
      - type: bind
        source: target/proxy.key
        target: /data/proxy.key
    depends_on:
      - cplane
      - postgres
